### ISSUE TITLE
Weights should not be drawn outside the bounding box when the bounding box/viewport is fixed

### ISSUE THREAD

**Issue by NAnguiano** [dondi/GRNsight#444] opened 2017-04-19 02:28 UTC
When a weighted graph is loaded and the "always show weights" option is selected, some of the weights are drawn outside the viewport. While this isn't so much an issue with the ability to scroll around, I figured I'd point it out in case this is something we wanted to change. I assume someone choosing fixed may not want to need to scroll outside the viewport.

![screen shot 2017-04-18 at 7 21 54 pm](https://cloud.githubusercontent.com/assets/6444156/25160679/52ecf344-246c-11e7-90cb-bd6aecc206c9.png)

You can see in this screenshot that is seems that GLN3 doesn't have a weight. The weight is actually drawn right outside the viewport, and can be seen if I scroll down.
![screen shot 2017-04-18 at 7 22 43 pm](https://cloud.githubusercontent.com/assets/6444156/25160694/7111776e-246c-11e7-8ad0-f0badaffa558.png)

With non-looping edges, if the two nodes are at a great enough distance and the edge is up against the top or bottom of the bounding box, the curving of the edge will cause the weight to be drawn out of bounds. Self-referential edges will always draw out of bounds if right up against the bottom of the viewport.
Here you can see these overlapping weights drawn out of bounds on the top:
![screen shot 2017-04-18 at 7 23 34 pm](https://cloud.githubusercontent.com/assets/6444156/25160726/a30a3f4e-246c-11e7-8813-e2e6550cdf54.png)
And here on the bottom:
![screen shot 2017-04-18 at 7 24 51 pm](https://cloud.githubusercontent.com/assets/6444156/25160745/bb086f08-246c-11e7-994f-e34e967a08c0.png)

I'm not sure if this is something we would want to fix or not, but I hadn't noticed it before and I'm not sure if this behavior is alright or not.

**Comment by kdahlquist** [comment] 2017-04-19 03:00
If the viewport/bounding box are fixed, then the weights should not go outside of edges.  "Fixed" implies that all drawable objects stay inside the viewable area.

However, I also want to say that I'd like to see #399 and #411 finished off (with the comments that @dondi and I made a couple of weeks ago) before diving into this one.

**Comment by kdahlquist** [comment] 2019-09-25 22:58
duplicate with #700; closing this one

**Comment by dondi** [comment] 2020-09-25 17:56
Wide range of possibilities to explore in case the “analytic” solution of individually adjusting edge weight label coordinates becomes unwieldy:
* Increase the margin for nodes and edges in the first place in order to give edge weight labels enough space to stay within bounds
* Experiment with font size in case a balance needs to be struck between margin and edge weight label size
* There are deeper solutions (e.g., collision detection) that would not be lined up for this release but may be good to keep on the radar while knowledge of this code is fresh

**Comment by igreen1** [comment] 2020-09-28 22:40
Commit #cb878d9 fixed this issue for non-self-referential edges. Rather than just moving the textbox for weight, the arcs of the edges of the graph are calculated such that they won't get too close to the edge. This solution was preferred since it also increases readability of the graph.
However, if the group wants, @igreen1 can also simply move the textbox within bounds for any given edge !

Commit #639acc4 fixed this issue on self-referential edges (those connecting to themselves) by not allowing labels to leave the viewport. The arcs were not redrawn because it was unnecessarily complicated for this case.

Adding review-requested tag :)

**Comment by dondi** [comment] 2020-09-29 02:05
@igreen1 These choices both look like they're worth a shot. Go ahead and issue a PR for it and we’ll see how it holds up to wider review once it’s on beta.

**Comment by kdahlquist** [comment] 2020-10-02 18:06
![image](https://user-images.githubusercontent.com/6463867/94955213-12674100-049f-11eb-9b2a-1344c762b138.png)

An artifact of this fix seems to be that the arc of the edge is altered from a circular/ellipse based curve to a sigmoidal curve.  Look at the blue edge between ABF1 and MSN1 in the screenshot above.

**Comment by dondi** [comment] 2020-10-02 18:18
Maintaining the arc look is a priority for GRNsight so @igreen1 will refine the calculations further in order to maintain arcs throughout.

**Comment by igreen1** [comment] 2020-10-02 18:33
#88edb5e changes the solution to move the weights and preserve the arc calculation.

@igreen1 will investigate the arc calculations more in depth, but for now this will solely move the weights

**Comment by kdahlquist** [comment] 2020-10-23 17:30
I just looked at this.  Can we increase the padding a little on this?  See how the edge weight at the bottom is not quite inside the bouding box.  It's still getting cut off a little.  Having a little white space between the edge weight and the bounding box of the viewport would be good.

![image](https://user-images.githubusercontent.com/6463867/97035128-be3e0280-151a-11eb-869e-b06d37b0ea9f.png)

**Comment by igreen1** [comment] 2020-11-09 22:58
Increased offset amount in commit #a9859e09418beca02ed703b08766cb1ff35030da
Changed the self-referential edge calculations slightly to reduce unnecessary calculations and variable overhead.

Image below shows the self-referential edge offset 

![image](https://user-images.githubusercontent.com/40191185/98606338-f162ee80-229b-11eb-9bc3-03311888d8c4.png)

**Comment by kdahlquist** [comment] 2020-11-13 19:02
confirmed fixed in beta v4.0.26

**Closed by kdahlquist** 2020-11-13 19:02 UTC
Labels: bug, functionality, graph layout, review requested
