### ISSUE TITLE
Make gray edges have dashed line instead of solid line

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#568] opened 2018-02-19 20:03 UTC
In keeping with making GRNsight more accessible for color-blind users, we want to make all the edges that are currently gray show up as dashed lines. 
- will have to figure out how to do the dashed line and choose the length of the dashes and spaces
- will have to be integrated with the grey slider so that if the grey slider is changed, the solid vs dashed is also changed.

**Comment by mihirsamdarshi** [comment] 2018-04-02 18:39
I finished this for all gray lines, I would like now to know if I should add an option to toggle this on or off, and how to do so, whether to re-render it every time the checkbox is clicked, or add it to the edit menu where the displaying weighted graph as an unweighted graph option is

**Comment by kdahlquist** [comment] 2018-04-02 19:02
We all voted to make it a preference, like the viewing weighted edges as colored edges.

**Comment by kdahlquist** [comment] 2018-04-17 16:57
I just tried this out on beta, but when I check the box for the dashed lines, the lines don't change.  What actually happens is that the lock force graph sliders checkbox also checks simultaneously, locking the sliders.  It seems that the dashed line check box is a duplicate of the lock sliders box, instead of independently doing a different function.

Also, side note for @yshin4, there is a bad interaction with the grid layout toggle.  When the sliders are locked, clicking the grid layout button does not change the layout to grid.

**Comment by eileenchoe** [comment] 2018-04-21 04:53
Fixed all bugs related to dashed lines, and they will be merged in with my node coloring PR #582

**Comment by eileenchoe** [comment] 2018-04-21 18:41
live on beta v.2.3.6

**Comment by kdahlquist** [comment] 2018-04-23 15:55
This appears to be working in beta 2.3.6, so closing.

**Closed by kdahlquist** 2018-04-23 15:55 UTC
Labels: review requested
