### ISSUE TITLE
Port GRNsight code to latest node-xlsx implementation

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#204] opened 2015-06-03 18:19 UTC
As observed in #177, there is a significant change in node-xlsx between the version that GRNsight is using at this writing and its latest version due to intellectual property issues. GRNsight should eventually use the latest version so that we are also free and clear here.

**Comment by kdahlquist** [comment] 2015-10-15 23:53
@NAnguiano will start this process as part of the preparatory work for node coloring #27

**Comment by NAnguiano** [comment] 2015-10-29 21:10
I'll begin doing this now, now that the data structure has been mostly confirmed (#241)

**Comment by anuvarsh** [comment] 2016-02-10 07:52
In order to take steps towards this process, I started looking for information that may provide insight regarding the specific changes made to the object produced by the older version of node-xlsx. Documentation on the node-xlsx GitHub Wiki has been minimal, and the little that I have found has not provided much clarification. Moving forward, I will make a few test excel sheets and play around with both versions to see if I can observe some of the changes that may need to be made. Meanwhile, more research for documentation will continue.

**Comment by NAnguiano** [comment] 2016-09-07 01:39
Got this working on a separate branch ("issue204"). One test is failing because it's taking too long to run, but the rest pass.

**Comment by kdahlquist** [comment] 2016-09-12 23:25
@NAnguiano reports that it is working.

We want the "one true beta" where issue204 is merged into beta and then merge master into beta.

**Comment by kdahlquist** [comment] 2016-09-19 22:52
All done except for the merging, so I'm going to close this.

**Closed by kdahlquist** 2016-09-19 22:52 UTC
Labels: functionality, priority 0
