### ISSUE TITLE
v4.0.0 Release

### ISSUE THREAD

**Issue by mihirsamdarshi** [dondi/GRNsight#767] opened 2019-06-06 00:00 UTC
This page summarizes the steps that need to be taken when performing the next major GRNsight release. Steps are manual for now, but documenting them is the first step toward facilitating automation in the future.

The list is coded up using checkboxes, so that its source can be copied into a GitHub issue as a starting point for preparing a new release.

- [x] In the days leading up to the release, all open issues that need to be resolved before the release will be given the label "for next release".
- [x] Any new or changed client-side features need to be documented on the [Client Side Testing Document](https://github.com/dondi/GRNsight/wiki/Client-Side-Testing-Document) page.
    - [x] the [featureList.json](https://github.com/dondi/GRNsight/blob/beta/documents/developer_documents/testing_script_generator/featureList.json) file should be updated
    - [x] the new feature also needs to be added to the [Pull Request Checklist](https://github.com/dondi/GRNsight/wiki/Pull-Request-Checklist)
- [x] Test the candidate build (typically the `beta` branch)
- [x] Merge the branch(es) under development (typically `beta`) into `master`
    - [x] Resolve any version control conflicts
    - [x] Test the final merged version
    - [x] Perform hotfixes on `master` as needed
- [x] Update README.md at top-level directory of master branch, if necessary
    - [x] Update Travis and Coveralls badges to reference the master branch
- [x] Tag the final, tested version as `v#.#.#` (all three numbers are required, even if `0`; see _npm_ step below)
    - [x] Update version numbers in _package.json_
    - [x] Remember that the tag needs to be pushed to GitHub: `git push origin <tag-name>`
- [x] Create draft release item on Github repository (name it exactly like the tag)
    - [x] Make release notes: a list of new features/bug fixes with issue numbers covered by this release.  Note that this at least will be the ones labeled "for next release", with possible others.
- [x] Publish GitHub release item
- [x] Publish release to GRNsight home page
    - [x] Refresh (pull) the `master` clone on _grnsight.cs.lmu.edu_
    - [x] Update the version number and modification date on `gh-pages`
    - [x] Update the About page with release notes (GitHub release item without issue numbers)
        - [x] Update the browser version compatibility statement with the latest version of Chrome and Firefox for which the new GRNsight version has been tested.
        - [x] Update modification date
    - [x] Add news item about the release to the News page
        - [x] Update modification date
        - [x] Link news item to the corresponding release notes in the About page
    - [x] Update Documentation page with any new features or updates to old features
- [x] Increment beta version
    - [x] Merge released `master` with `beta`, especially if hotfixes/merges were made on `master`
    - [x] Update version number and modified date on `gh-pages`
    - [x] Update Travis and Coveralls badges to reference the beta branch
    - [x] Refresh (pull) the `beta` clone on _grnsight.cs.lmu.edu_
- [x] Publish to _npm_ (`npm publish`)
    - [x] _npm_ requires all `.0`s in the semantic version
    - [x] Check to see that BioJS updates its GRNsight entry
- [x] Update version number/other relevant information at current bioinformatics listing sites
    - [x] Elixir 
        - [x] Then change hyperlink on the GRNsight Links page, if necessary
- [x] Get DOI for new release from Zenodo
    - [x] Verify that the badge in README.md at top level of repo is correct
      (it might be necessary to invoke `curl -X PURGE https://camo.githubusercontent.com/`_camo-GitHub-id_ in order to update the badge image)
    - [x] Verify that CITATION.md file DOI links to the new release, updating if necessary
    - [x] Verify that "How to cite GRNsight" section on About page links to the new release, updating if necessary

**Comment by kdahlquist** [comment] 2019-06-07 18:10
@mihirsamdarshi has put up a draft release with release notes.  @kdahlquist will now review while @mihirsamdarshi is looking into #777.

**Comment by kdahlquist** [comment] 2019-06-07 19:05
I've finished editing the release notes.  The only thing to add would be a reference to #777, if that gets added to the release.

**Comment by kdahlquist** [comment] 2019-06-07 22:01
@mihirsamdarshi, are you still in the building somewhere?  If not, are you coming back here? What is our go/no go status for release? Are we going to punt on #777 and release anyway?  Let me know.

**Comment by mihirsamdarshi** [comment] 2019-06-07 22:09
Yes, I am outside taking advantage of the sun. I believe I have a fix for #777, and am working on it right now

**Comment by mihirsamdarshi** [comment] 2019-06-07 22:19
@kdahlquist I figured out the problem, and have created a fix, although it doesn't necessarily work all the time. I want to call it here, and table this bug for now. I can push a hot fix sometime this weekend.

**Comment by dondi** [comment] 2019-06-07 22:23
@mihirsamdarshi Please leave behind some specifics on what doesn’t necessarily work all the time, in case you are unable to get to it after today. Context, steps to reproduce, etc. Thanks!

**Comment by mihirsamdarshi** [comment] 2019-06-07 23:17
Got it, I added it to the appropriate issue. I am going to issue a beta -> master PR

**Comment by mihirsamdarshi** [comment] 2019-06-07 23:18
The News, About, and Documentation pages have been updated and I just need to push them.

**Comment by mihirsamdarshi** [comment] 2019-06-08 23:32
@dondi everything I was able to do has been done, the remaining items on the checklist I believe you can accomplish, unless I am wrong

**Comment by dondi** [comment] 2019-06-09 22:38
Release update: I’m working on updating the server to 4.0.0 but have hit the snag. Help from Masao is pending.

The long and the short of it: `git` is failing because it is running out of memory. Apparently, processing the accumulated changes since the last release requires more memory than `grnsight.cs.lmu.edu` currently has.

I have asked Masao to upgrade the machine (if only temporarily, just so the `git pull` operation can finish). I will update the status as it develops.

**Comment by dondi** [comment] 2019-06-10 01:02
Memory issues fixed; production is back online, at version 4.0.0.

**Comment by dondi** [comment] 2019-06-16 21:34
All post release tasks have been completed. BioJS has a new website, so I updated the Links page accordingly. In addition, the About page had lost its formatting; there was a typo in the Jekyll template header. I’ve fixed that too.

All Zenodo links updated automatically. The only link that did not appear to update automatically is OMIC Tools: https://omictools.com/grnsight-tool —it lists @kdahlquist as the maintainer, so is this one yours to update?

**Comment by kdahlquist** [comment] 2019-06-17 00:52
I will give it a look on Tuesday. Too busy on Monday.



Kam D. Dahlquist, Ph.D.
Professor of Biology
Loyola Marymount University

-------- Original message --------

**Comment by kdahlquist** [comment] 2019-09-25 21:45
I sent OmicX a message via their website to find out how I can update it.  They have actually started charging for their platform.  So I think we need to reevaluate whether we should be directing traffic to their site by linking to it.

**Comment by dondi** [comment] 2019-09-25 22:10
Based on changes to OmicX (particularly into a pay service), we have eliminated the link to them from the GRNsight webstie and so we can close this issue.

**Closed by dondi** 2019-09-25 22:10 UTC
Labels: for next release, priority 0

**Comment by kdahlquist** [comment] 2019-09-27 14:55
OmicX updated their site due to my e-mail.  If we want to maintain it, we will need to e-mail them directly in the future, I think.
