### ISSUE TITLE
Dropdown menu and sidebar menu viewport sizes do not initialize to same values

### ISSUE THREAD

**Issue by mihirsamdarshi** [dondi/GRNsight#599] opened 2018-05-14 22:55 UTC
Dropdown menu and sidebar menu viewport sizes do not initialize to same values

**Comment by kdahlquist** [comment] 2018-05-14 22:58
Dropdown menu and sidebar menu viewport sizes do not initialize to same values

@mihirsamdarshi, when reporting bugs, will you:
- copy title into description field instead of leaving blank
- add labels `bug`, `priority 1`, `functionality`

Thanks.

**Comment by kdahlquist** [comment] 2018-05-31 19:33
@mihirsamdarshi will try to reproduce this bug; it might be fixed--it didn't show up on @kdahlquist's computer with Firefox.

**Comment by kdahlquist** [comment] 2019-02-26 23:12
Can't reproduce this bug on v3.1.12, so closing, adding label backlog, in case it comes back.

**Closed by kdahlquist** 2019-02-26 23:12 UTC
Labels: bug, functionality, priority 0.5
