### ISSUE TITLE
D-pad, zoom slider, and cursor drag do not move graph after export to SVG

### ISSUE THREAD

**Issue by ceciliazaragoza** [dondi/GRNsight#1093] opened 2024-02-13 07:35 UTC
After exporting a graph to SVG, the D-pad can be clicked and the zoom slider can be moved. However, the cursor hand does not close, and the graph does not move and remains at the same zoom and position as when exported. However, if you reload the graph, choose a demo, or open a file, the cursor grab and zoom slider move the graph again. This issue is in the master branch as well.

**Comment by dondi** [comment] 2024-02-13 18:44
Suspicion here is that the export routine manipulates the SVG elements in-place to make them export ready but those changes then impact the web app. Ideally the SVG export operates on a deep copy of the SVG tree so that it doesn’t leave any unintended side effects

**Comment by ceciliazaragoza** [comment] 2024-04-02 16:59
This seems to be the same issue as in #1059.

**Comment by dondi** [comment] 2024-04-02 17:21
To elaborate further, #1059 may be the root cause of this bug; that is currently assigned to @ntran18. @ceciliazaragoza will monitor both issues and update accordingly if it does turn out that they are bound together

**Comment by kdahlquist** [comment] 2024-11-13 20:54
Verified fixed in beta 7.1.7

**Closed by kdahlquist** 2024-11-13 20:54 UTC
Labels: bug, priority 0, review requested
