### ISSUE TITLE
On beta 3.1.11, slider lock check box is not working

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#736] opened 2019-02-19 22:22 UTC
On beta 3.1.11, slider lock check box is not working; can't review #592 until this is fixed.

**Comment by dondi** [comment] 2019-02-26 22:05
After some triage, we were able to find the root cause (interference by code later in the function). @mihirsamdarshi will enforce the "single source of truth" purpose of `grnState` to make sure that the state of the lock checkbox always follows what `grnState` says that should be.

**Comment by dondi** [comment] 2019-03-26 21:08
Code appears to be done but not released to beta. May require a new release so that the issue can be closed.

**Comment by dondi** [comment] 2019-03-26 21:35
Fixed on beta 3.1.13.

**Closed by dondi** 2019-03-26 21:35 UTC
Labels: bug, functionality, priority 0
