### ISSUE TITLE
Database project UI

### ISSUE THREAD

**Issue by afiller1** [dondi/GRNsight#837] opened 2020-02-03 08:39 UTC
## FINISH BY 3/16/2020
 - [x] Design UI where client can interact with database

## FINISH BY 3/31/2020
 - [x] Implement this UI

**Comment by afiller1** [comment] 2020-03-30 04:26
I have come up with an idea for a UI that will allow the user to interact with the database effectively. First, along the bar at the top that contains the "File, Layout, Node, Edge ... " dropdowns, I want to put a "Data" dropdown option (we discussed this in a meeting at one point; this dropdown could potentially house functionality for both my own as well as Kevin's projects). Under this, I'd want to put an option the user can select titled "Node Coloring Using Expression Database." Under this tab, I envision a row of options appearing below the "File, Layout, Node..." bar that will allow the user to select a Data Set, a Strain, and Timepoints from separate dropdown menus (where the user can potentially select multiple of each). These selections will allow the API to query the database appropriately and return the desired data for node coloring. There could potentially be a Gene option that the user can select as well, if they wish to select which genes they want to form an Expression Data sheet for. The user should also have the option for all of these fields to be selected automatically based on a network sheet that they have uploaded.

**Comment by kdahlquist** [comment] 2020-03-30 04:31
That sounds good.  You would have to restrict the choices for strain and timepoints based on the dataset selected.

I think that we should keep it simple and allow them to query based just on the genes that are in the displayed network for now.

**Comment by afiller1** [comment] 2020-04-06 16:09
I made a rough go at the UI. It's not connected to any functionality yet, but I wanted to create a basic skeleton so I can at least have something to work with/make adjustments to as I'm writing my DB calls.

**Comment by dondi** [comment] 2020-04-06 16:40
@afiller1 did a screen share showing the prototype UI. @kdahlquist provided some early comments but we’ll go more in-depth when this is available on beta.

**Comment by dondi** [comment] 2020-04-06 16:51
The core change we are inserting is the ability for the user to choose a different source for expression data. Thus, the UI demoed by @afiller1 should go under a "select source" functionality that belongs inside the Node Coloring panel. User can be shown the current selected source (which can be "none") then a button/control will allow the user to make a different selection. Top-level choice is workbook (if available) + known sources in the database (and this is where a corresponding API endpoint would come in).

Once the user has made a choice, the selection(s) will then affect the rest of the node coloring settings as well as parameters that are passed into the API.

**Comment by afiller1** [comment] 2020-04-06 16:52
![ui_screenshot_1](https://user-images.githubusercontent.com/21373644/78583882-457c9080-77ec-11ea-8db7-29d6fa63c340.PNG)

**Comment by afiller1** [comment] 2020-04-11 20:05
@dondi I have the front end behaving pretty much how I want, but I'm having an issue with the "Enable Node Coloring" checkbox in the Node sidebar section. What I ideally want it to do is, when that check box is clicked and I'm using expression database data, is make the database call with the appropriate query based on what the user has selected and then do node coloring based on that. However, I can't find where anything is actually activated based on when the checkbox is clicked. The if statements all seem to depend on when grnState.nodeColoring.nodeColoringEnabled is true, but I can't find where the checkbox click itself affects whether that value is true or false, which seems to make sense to me. I'm a bit stuck on this point, if you get a chance to clone my branch and have a peek.

**Comment by dondi** [comment] 2020-04-11 20:26
After the big MVC refactor, I would expect this code to be in _setupHandlers.js_. Have you looked there? Events might be `change` or `click`. Another approach is to look for the selector of the checkbox (id, class, or both) to see where it is referenced (it may be mapped to a constant).

A more remote possibility is that there are no specific handlers for this, and the graph is just made to refresh. In that case, feel free to write your own change handler for it in _setupHandlers.js_.

**Comment by afiller1** [comment] 2020-04-12 03:53
I was able to resolve this.

Now, I am able to insert the expression data into the whole big network object, but I'm having an error saying there's no data attribute of undefined at grnState.nodeColoring.topDataset. Is there a specific structure that grnState.nodeColoring.topDataset is supposed to follow? Or is grnState.nodeColoring.topDataset.data just the same as my expression object's data attribute? If you know off the top of your head or have a chance to take a peek, @dondi .

**Comment by dondi** [comment] 2020-04-12 03:57
I don’t know this part off the top of my head. Try putting a console log at the offending line, then load one of the demos. See what gets logged for that one and compare it to what happens when you load from the database.

**Comment by afiller1** [comment] 2020-04-19 20:10
@kdahlquist We initially said we want an option so that the user can select the timepoints they want displayed from the expression db, but that option doesn't currently exist for when the user uploads a sheet with existing expression data... So do we still want to add a timepoints selection option for the expression db, or should that be a small feature added at a later time so that the user can select the timepoints whether they've uploaded a workbook with expression data or not?

**Comment by kdahlquist** [comment] 2020-04-20 03:17
I think we can add choosing timepoints later.Kam D. Dahlquist, Ph.D.Professor of BiologyLoyola Marymount University
-------- Original message --------From: Alexia <notifications@github.com> Date: 4/19/20  1:10 PM  (GMT-08:00) To: dondi/GRNsight <GRNsight@noreply.github.com> Cc: Kam Dahlquist <kdahlquist@lmu.edu>, Mention <mention@noreply.github.com> Subject: Re: [dondi/GRNsight] Database project UI (#837) 
@kdahlquist We initially said we want an option so that the user can select the timepoints they want displayed from the expression db, but that option doesn't currently exist for when the user uploads a sheet with existing expression data... So do we still want to add a timepoints selection option for the expression db, or should that be a small feature added at a later time so that the user can select the timepoints whether they've uploaded a workbook with expression data or not?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/dondi/GRNsight/issues/837#issuecomment-616217393",
"url": "https://github.com/dondi/GRNsight/issues/837#issuecomment-616217393",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by afiller1** [comment] 2020-04-20 04:12
I've made it so the data that is used for node coloring is updated based on what the user selects. I also added a loading icon for when the data from the database is loading.

**Comment by kdahlquist** [comment] 2020-04-22 18:53
@afiller1, how long is it supposed to take loading?  I'm trying to look at it now, but it's been spinning for about 10 minutes.  I'll make some comments on the UI, even though the data is not loading for me.  I don't know if all did something to the backend connection yet.

1. I think that if a user uploads a workbook with no expression data, the default for the checkbox should be unchecked, i.e., Enable Node Coloring should be turned off.
2. Right now, the enable node coloring check box does not respond to my click.
3. Please make your instruction message left-justified instead of centered.  
4. Please change the wording sligtly to:
    "Select from user-uploaded expression data, or use data from our Expression Database"
5. Something I noticed, the color bar legend only shows up if node coloring is actually happening, but the field to reset the max value is always there.  Maybe the color bar legend should also just be there all the time, too.
6. The message "Node Coloring is Loading" should read "Expression Database is loading"

That's all I have for now because it's not loading for me at this time.

That's all I see for now.

**Comment by afiller1** [comment] 2020-04-26 06:33
Yeah, I probably turned off the DB instance by then to avoid running my credits down too much. It only takes a few seconds to load. Currently working on these requests.

**Comment by kdahlquist** [comment] 2020-04-28 16:56
Not sure where to put this comment.  I'd like to reword the warning that happens when a user uploads a file with no expression data.  It currently says:

"_log2_expression or _log2_optimized_expression worksheet was not detected. The network graph will display without node coloring. If you wish for the network to be colored, you can upload your own expression data, or use options from our Expression Database."

Please change to:
"_log2_expression or _log2_optimized_expression worksheet was not detected. The network graph will display without node coloring. If you want the nodes to be colored with expression data, you can upload your own expression data by adding one or more of those worksheets to your Excel workbook or select from data in GRNsight's Expression Database, found in the Node menu or panel."

**Comment by afiller1** [comment] 2020-04-29 22:18
Done. This should show up on beta in my next PR.

**Comment by afiller1** [comment] 2020-04-30 02:32
I propose closing this issue since my initial tasks for this issue have been completed. Additional problems/bugs can be reported in specific issues. This will help us to pinpoint individual tasks and ensure that details don't get lost in further comments! @dondi @kdahlquist

**Comment by kdahlquist** [comment] 2020-04-30 02:38
Has the PR that changes the warning message been issued yet?  That task from this issue is still open.  Let's wait until that loose end is tied up.  I will start other issues for anything new, though.

**Comment by afiller1** [comment] 2020-05-01 00:34
The PR is out, it just hasn't been pushed to beta. And ok, I will keep an eye out for new issues.

**Comment by kdahlquist** [comment] 2020-05-01 05:57
Confirmed that reworded warning appears.  Closing.

**Closed by kdahlquist** 2020-05-01 05:57 UTC
Labels: CMSI402, feature request, functionality, priority 0, review requested
