### ISSUE TITLE
Sidebar redesign

### ISSUE THREAD

**Issue by mihirsamdarshi** [dondi/GRNsight#609] opened 2018-05-15 20:11 UTC
The sidebar is fairly complex right now, and this calls for a major redesign. This could go hand in hand with a potential move from jade to pug or perhaps something like ReactJS

**Comment by kdahlquist** [comment] 2018-05-15 21:41
One idea is to make collapsible sections:  #463:
- Make the force graph parameter sliders, sizing, showing/hiding weights into collapsible sections.
- What is in the collapsible sections should also be redundant with what's in the menu.

Another idea is palettes like in Adobe Illustrator or Photoshop.

Or just hiding/showing consistently when relevant.

**Comment by kdahlquist** [comment] 2019-11-21 19:11
Closing this because duplicate of #803

**Closed by kdahlquist** 2019-11-21 19:11 UTC
Labels: duplicate, enhancement, functionality, priority 1
