### ISSUE TITLE
Disabling node coloring will be enabled upon reload 

### ISSUE THREAD

**Issue by ahmad00m** [dondi/GRNsight#943] opened 2021-12-10 00:15 UTC
The settings should remain as it is when reload bottom is used. However, The node coloring will be enabled upon reload. Also, any other setting that changes upon reload needs to be fixed so it doesn't change after reload. Moreover, another feature can be created to reset the setting/graph together.

**Comment by dondi** [comment] 2022-01-18 21:13
This bug will be helpful in getting acquainted with the overall application code structure. Start by tracking down the code for the _Enable Node Coloring_ checkbox and look at how it interacts with the `grnState` variable. Then look at the _Reset_ command and track down how it appears to be resetting

**Comment by dondi** [comment] 2022-01-18 21:21
A library that may be useful to know about in the background is [jQuery](https://jquery.com)

**Comment by Sarronnn** [comment] 2022-01-30 23:15
Could not get the graph to show up: do I need to upload a gene sequence?

Looked at developers tool: Error message showed
"Failed to load resource: the server responded with a status of 404 (Not Found)"
" DevTools failed to load source-ma

**Comment by kdahlquist** [comment] 2022-01-31 16:56
You should be able to reproduce this by using a demo file under the demo menu.

**Comment by Sarronnn** [comment] 2022-01-31 20:31
I tried the files under demo:
- The graph does not show up on the **local** GRNsight, but it does on the actual one .

**Comment by Sarronnn** [comment] 2022-03-21 03:32
Looked at graph.js and grn.state.js to locate the bug.
Moved on to look at update-app.js.
- Maybe here? Ask is it because _grnState.nodeColoring.nodeColoringEnabled_ is set to _true_??
![Screenshot (46)](https://user-images.githubusercontent.com/89826597/159201731-4af3ddfe-93b7-4af6-8747-1de251433c23.png)

**Comment by dondi** [comment] 2022-03-28 23:55
@Sarronnn are there any updates on learning about this bug?

**Comment by Sarronnn** [comment] 2022-04-04 20:51
if (hasExpressionData(grnState.workbook.expression)) {
            resetDatasetDropdownMenus(grnState.workbook);

            grnState.nodeColoring.nodeColoringEnabled = false; //was true before
Update: Did not work
Currently: Still looking at the code in detail for possible bug defects.
Question: As I make the edit on my editor, and save the changes, I am able to run the local version and see those changes right?

**Comment by dondi** [comment] 2022-04-04 23:35
In answer to the question, yes, saving changes in the editor should make `npm run start-dev` refresh (actually you should also to see the refresh taking place in the command line), but frequently you need to reload the browser window so that the new code gets loaded into the browser

For pursuing whether a possible fix is in the direction, you’ll want to make the code’s execution more “visible” to you. There are two broad options to do this:
- Make use of the browser’s debugger
- Make use of `console.log` so that you can see a printout of where the code is going

This way you can get a finer view of what is happening internally and eventually home in on the potential issue. We can go over this live at some future time

**Comment by dondi** [comment] 2022-04-04 23:38
Before we meet, the first thing to get used to is executing your local copy with the developer tools open and seeing if you can get console logs to appear after you modify your local code with them

**Comment by Sarronnn** [comment] 2022-04-10 21:22
![Screenshot (7)](https://user-images.githubusercontent.com/89826597/162640445-eea40da1-06f3-45de-be6b-ddb3a474365a.png)

**Comment by dondi** [comment] 2022-04-10 21:28
Yes, when quotes are not used, the expectation is that there is a variable with that name, and there isn’t any at that point thus you get the error

The error that goes with print has a couple of reasons: first, JavaScript does not use print (it is console.log instead) and second, parentheses are always required with function calls

Now that you have the right form worked out, put those statements right in the code then reload the app to see if they come out while the app is being used

**Comment by Sarronnn** [comment] 2022-04-11 05:08
Got it, thank you for the feedback!
Update: 
- searched keywords "Nodecoloring" and set those values to false.
- Changes were not associated with bug
Question:
- I was thinking, there has to be a function that lets the user reload.
- So I tried searching up the keyword "reload" but no luck there.
- Is there a function that deals with the user reloading the page?

**Comment by dondi** [comment] 2022-04-11 23:42
We answered @Sarronnn’s question on a reload function by using _Inspect_ in the browser on the Reload item and noting its ID which was `#reload`. We then searched the code for that and found what appears to be the starting point of the reload sequence: https://github.com/dondi/GRNsight/blob/master/web-client/public/js/setup-load-and-import-handlers.js

@Sarronnn will start using temporary `console.log` technique for following the code from there and will see if she can spot the places where values are being adjusted

**Comment by dondi** [comment] 2022-04-11 23:46
Upon further inspection, we found a constant called `NODE_COLORING_TOGGLE_SIDEBAR` which appears to represent the checkbox in the sidebar, and its value appears to be hardcoded to `true`: https://github.com/dondi/GRNsight/blob/master/web-client/public/js/update-app.js#L802

**Comment by Sarronnn** [comment] 2022-04-18 20:18
![Screenshot (64)](https://user-images.githubusercontent.com/89826597/163864991-1615bf4f-c9c2-42d6-9d79-62475d34a000.png)
Question
- How to unhardcode it?
I'm guessing this is saying if the workbook is not empty and node coloring is NOT enabled
   - "checked" refers to the tick mark on node coloring, it doesn't mean its turning off/on the node coloring?
- Or do we need an if statement saying
   else if (grnState.workbook !== null && !grnState.nodeColoring.nodeColoringEnabled
      &&  $NODE_COLORING_TOGGLE_SIDEBAR.prop("checked", false); {
     // then !grnState.nodeColoring.nodeColoringEnabled;

**Comment by dondi** [comment] 2022-04-18 23:38
In answer to the comment above, it looks like applying a pattern like this will address the issue:
```javascript
if (grnState.nodeColoring.nodeColoringEnabled) {
    $(NODE_COLORING_TOGGLE_SIDEBAR).prop("checked", "checked");
} else {
    $(NODE_COLORING_TOGGLE_SIDEBAR).removeProp("checked");
}
```

Try that out and see if it has the desired effect; also search the code for `NODE_COLORING_TOGGLE_SIDEBAR` in case this selector is being used in other parts of the code, as well as `nodeColoringEnabled` to see what other parts of the code are using this `grnState` property

When you get this to work, let’s aim to have you issue a pull request so we can this fix onto beta (and eventually onto v6.0.0)

**Comment by Sarronnn** [comment] 2022-04-22 00:47
Went to ask Prof.Dondi for help:
- We set NodeColoringEnabled to undefined
- We set it to true only the first time the user loads data.
- The bug was fixed

**Comment by dondi** [comment] 2022-04-25 23:31
Some listing errors noted; just trailing spaces on five lines. @Sarronnn will fix this then push, then upon getting the green check, will open a pull request that merges into `beta` (not `master` yet)

**Comment by dondi** [comment] 2022-09-07 19:30
Linting fixes committed with https://github.com/dondi/GRNsight/commit/840e26d15f434933b2c639140b086fe1449d4d41

**Closed by dondi** 2022-09-07 19:30 UTC
Labels: bug, priority 0, review requested
