### ISSUE TITLE
Initial Setup 

### ISSUE THREAD

**Issue by ntran18** [dondi/GRNsight#1014] opened 2023-01-18 05:45 UTC
- Missing command line for running GRNsight in Development Mode: 
   - Get `parallelshell --wait "nodemon web-client/app.js" "nodemon server/app.js" "webpack --watch --mode=development"` after running `npm run start-dev`
  - Solution: Type `sudo npm i -g parallelshell` to install parallelshell, `sudo` is for administration
  - We can link the trouble shooting page to the Initial Setup page
- Can't run Development Mode but already installed database
- Doesn't have node_modules folder even run `npm install`
<img width="1037" alt="Screenshot 2023-01-17 at 9 39 31 PM" src="https://user-images.githubusercontent.com/108908370/213093160-ccfc6157-8cb8-4e9c-bddc-e8e5e9b7ae31.png">

**Comment by kdahlquist** [comment] 2023-01-18 20:20
Is this connected to the node version issue? #1013 

"-g" is not recommended because that stands for global, so whole computer has parallelshell.  Need to install locally.  It should come down with npm install.  Also don't install with "sudo".

Once correct version for node is figured out, then @ntran18 can restart and see if solves problem.

**Comment by kdahlquist** [comment] 2023-01-25 20:27
@ntran18 is still stuck on this.  Need to change node version; changing path variable when multiple instances of node are installed suffices.  She needs to install node 14 and be able to switch between them.

**Comment by kdahlquist** [comment] 2023-01-25 20:30
check current version of node first (which is 18)

brew install node@14

when installation ends, there will be instructions at the bottom on how to change versions

**Comment by ntran18** [comment] 2023-01-31 05:06
I installed node@14 and run the command `export PATH="/opt/homebrew/opt/node@14/bin:$PATH"` to run temporary node version 14 and install npm. However, I still can't run `npm run start-dev`. The same problem occurs

**Comment by dondi** [comment] 2023-02-01 05:04
Interesting—I was about to report that using `node@14` on a clean clone, with `PATH` set accordingly, worked completely as expected for me. `npm install` succeeded and `npm run start-dev` ran without an issue

@ntran18 I’m beginning to suspect that the prior `-g` installs might be in the way for you. Let’s look into clearing that out

**Comment by ntran18** [comment] 2023-02-02 02:53
The error I got was `Error: listen EADDRINUSE: address already in use :::5000`; however, @dondi helped me to fix that by turning off Airplay receiver in the settings.

**Comment by dondi** [comment] 2023-02-08 06:40
Yes, it’s at the bottom of Initial Setup. We can consider another option for this—if this port usage is here to stay, we can look into changing our own port to something else

**Comment by ntran18** [comment] 2023-02-14 19:55
For the documentation, I think we can update it a little bit for instructions:
- Dependency Installation 
   -  Tell the version of the npm 
   -  Instruction on how to install the other version of npm and how to change the version
   -  If the instruction is to change the path temporarily by using this command, `export PATH="/opt/homebrew/opt/node@14/bin:$PATH"`, then we have to change the npm version every time we run the project in a. new window. 
- Database Setup
   - In the GRNsight Database README.md, there is a link to a presentation. We should organize again what is needed to be on the presentation. (like slides 7 and 8, we don't need to have) 
   - Another question is, do we need the presentation? Because all the steps already listed in README.md

**Comment by dondi** [comment] 2023-02-15 20:29
@ntran18’s setup is nearly complete except that the Network Source dropdown is showing `undefined` for the source name rather than YeastMine. When @dondi inspected the database, the schemas looked like they were there and the tables looked like they had the expected information

@ntran18 will consult with @Onariaginosa and @ahmad00m on this—@ahmad00m said this looks familiar

Once the issue is isolated, this may result in either a code change or a documentation revision, or both

**Comment by dondi** [comment] 2023-02-15 20:31
After review of the suggested documentation changes (one suggestion: change the sample path to something more generic rather than Homebrew), @ntran18 can implement the revisions directly

**Comment by ntran18** [comment] 2023-02-22 06:09
I updated on Initial Setup page for the installing older version of node on macOS

**Comment by kdahlquist** [comment] 2023-02-22 20:01
@ntran18 is still working on documentation on how to load the database.  She's going to edit the PDF from the databases class and select only the items necessary for GRNsight and add it to the wiki.

**Closed** 2023-02-22 20:03 UTC
Labels: priority 0
