### ISSUE TITLE
Database project general backend

### ISSUE THREAD

**Issue by afiller1** [dondi/GRNsight#838] opened 2020-02-03 08:41 UTC
## FINISH BY 3/30/2020
 - [x] Connect database to GRNsight
 - [x] Write APIs to run specific queries to the database (tba)
 - [x] Add export to Excel functionality

**Comment by afiller1** [comment] 2020-03-02 04:30
I have been looking at how to connect an application to an RDS instance programatically, and these are the best sources I have been able to find. @dondi , would you mind telling me if any of these seem to be pointing in the correct direction?
- https://aws.amazon.com/blogs/database/query-your-aws-database-from-your-serverless-application/
- https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Using_the_Query_API.html
- https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/Welcome.html

**Comment by dondi** [comment] 2020-03-02 05:02
The Serverless approach via AWS Lambda is the way that I know of the most, and Dr. Toal knows even more. We can see if we can sit with him and perhaps bootstrap you on it. He builds APIs in Python using Flask and psycopg to connect to the database. Deployment is done via a package called Zappa.

That’s a lot of names to hear about but once the pieces are together, you’ll be able to focus on database interaction from that point.

AWS Lambda can also run node JS code, but we don’t have as much firsthand knowledge of that as with a Flask Python stack.

Meanwhile, you can read up on RESTful APIs and start planning out this one. What endpoints will we need? With what parameters? They don’t have to be set in stone—in fact they can be quite fluid while you work on them—but it will still be useful to start with a general sketch.

**Comment by afiller1** [comment] 2020-03-02 06:38
Based on your comment, I have taken time to read up on REST APIs, and I have thrown some notes into a wiki page [here](https://github.com/dondi/GRNsight/wiki/Basics-of-REST-APIs) based on some helpful resources I found.

In terms of endpoints and whatnot, this is what I have in mind so far (and I would like to discuss this during our meeting):
- an endpoint that returns the full data from any desired table (I imagine we want some sort of functionality where the user will be able to view the data we have in its totality if they desire). This will require parameters such as the table they wish to view, and perhaps the number of fields/entries they may wish to view.
- an endpoint that returns data of a specific gene (since we mentioned that would be helpful in producing useful expression data for node coloring). This will require a parameter that takes in a gene name and runs a query in our database based on that.
- an endpoint that returns data from just a specific publication. This will require a GEOID parameter that will map to that specific publication.
- an endpoint that returns data for just a specific strain of yeast. This will require a parameter that takes in the yeast strain and returns data based on that.

We mentioned before having the list of expression data options in a drop-down menu or something. I believe some of these queries will take care of that functionality and map to specific expression data based on various parameters... Although I do want to discuss in the meeting which will be most useful for our intended user.

In addition to all this, I will plan a meeting this week with Dr. Toal and Dondi to figure out exactly how to use AWS Lambda to make the connection we need between GRNsight and our database. Once this connection is set up, writing the APIs and queries should be decently understandable, I hope.

**Comment by kdahlquist** [comment] 2020-03-02 17:16
I'm thinking right now that we do not need full functionality for the user to query the database.  The primary use for it at the moment would be the following:

1. Select data for node coloring for the currently displayed network.  This would involve selecting the dataset, strain (if there are multiple strains in a dataset), timepoints.
    - So think about what data is required to color the nodes, and set up a system to query for that.

2. Select data for populating a GRNmap workbook for export.  It would involve the information above, but adding in the degradation rates and production rates for the genes in the currently displayed network.
    - Again, think about what data would be required to populate the workbook, and set up a system to query for that.

@dondi can chime in, but for the moment, I don't thing there is a reason why the user needs to view the data tables.

In the future, we could think about pulling from the expression database to display data on the gene pages, but that would be for the future (not within the scope of the current 402).

**Comment by dondi** [comment] 2020-03-02 18:03
@dondi reviewed @afiller1's notes on RESTful APIs and confirmed that this is good general knowledge to have. In terms of priority, we will adhere to the two key functions listed by @kdahlquist above.

We walked through an overall system diagram of how things will look like when finished (@afiller1 took a picture) and established the following sequence:
1. @afiller1 will be on a learning curve temporarily as she learns how to set up a rudimentary API connection to the database
2. While learning this, concurrently, she can start determining the SQL queries that will produce the data listed by @kdahlquist as the two initial top priorities (and we will focus all development in the completion of just those two priorities initially)
3. @dondi mapped in the diagram how the results of these queries (a) will determine what parameters are needed for the two endpoints that correspond to these priorities and (b) will get converted into JSON that is compatible (ideally identical) to the JSON derived from workbooks
4. The process of determining the SQL queries may result in some database redesign, but that is a natural aspect of this iterative process

**Comment by afiller1** [comment] 2020-03-02 18:03
![Image from iOS (6)](https://user-images.githubusercontent.com/21373644/75703741-ec5d9200-5c6c-11ea-9d2e-8dde9da215b8.jpg)

**Comment by dondi** [comment] 2020-03-02 18:06
@afiller1 is likely to implement the API server + database query with NodeJS, in which case learning the Sequelize library would be recommended, as well as how to deploy a Lambda with NodeJS.

**Comment by afiller1** [comment] 2020-03-03 03:28
I worked with @dondi and Dr. Toal to attempt to start a Lambda instance. All the Flask setup commands worked. Ran into some issues when trying to deploy Zappa. Lambda doesn't seem to be fully populated on my account... Will try and get in touch with AWS services to figure out what the problem is (are AWS Educate accounts restricted in how much they can do with Lambda? Or did we just miss a step in the setup process?). Dondi, feel free to input any other notes from this session in case any details have slipped my mind.

**Comment by afiller1** [comment] 2020-03-19 00:00
@kdahlquist do you think you can point me to a wiki link or any helpful page that lays out which data is used in node coloring and how it's used? I'm examining the code right now, but if you have a link on hand, that would be very helpful as well.

**Comment by kdahlquist** [comment] 2020-03-19 00:48
@afiller1, I'm not sure what exactly you are looking for.  I have information on what data is included in the Excel workbook from GRNmap, but I just looked on the GRNsight wiki and there isn't anything there.  I vaguely remember @eileenchoe had a page about it, but I can't find it right now.

Basically, the node coloring is using the expression sheets or the optimized_expression sheets.  The names of the worksheets available to use for coloring are in the drop-down menus the user can choose from.  The user can choose to average replicate datapoints or not (for example averaging the values for all the columns that say "15" or leaving them as individual stripes.  The colors are chosen based on the scale, the default range is -3 to 3.

What else do you want to know?

**Comment by dondi** [comment] 2020-03-19 01:24
@afiller1 Everything should be in the JavaScript object that you get back after uploading the workbook. It shows up in the console. There is an `expression` property in that object, and that’s pretty much everything.

I’ll post the full JSON for that on Slack so you can confirm that what you see on the console is what I’m referring to.

**Comment by afiller1** [comment] 2020-03-19 19:32
Ok. In which case, I have a couple questions about the queries made to the database.

As Dr. Dahlquist lays out above, we want to be able to "Select data for node coloring for the currently displayed network. This would involve selecting the dataset, strain (if there are multiple strains in a dataset), timepoints." When we say it's for the currently displayed network, does this mean the data used to make the display contains only the network sheet? Where exactly will the "current network" contain the dataset, strain, and timepoint info we will need in order to make the appropriate query to the database? Will we also need to take in consideration the specific genes outlined in the network sheet?

The "Select data for populating a GRNmap workbook for export" task is a bit easier to envision; I assume we will want to give the user options for which dataset, strain, and timepoints (and genes?) that they can select that we can use to populate a GRNmap workbook. So the queries for that will be based on the fields they select, right?

I think many of my questions would be answered if we could walk through some specific user stories for this feature; perhaps we can do that on Monday.

@dondi @kdahlquist

**Comment by dondi** [comment] 2020-03-19 19:42
@afiller1 Actually I foresee both tasks as needed the same information. So whatever the GRNmap workbook export will need, will also be needed in order to do node coloring. The one difference is that information like the species, strain, or dataset may already be available from the uploaded workbook. Genes will be available from the network. But ultimately the same information is needed by both use cases. It’s just that sometimes, this information might already be inferable from the current workbook.

So the flow would be:
* Be aware of the information that is necessary
* If the information can be derived from the most recently uploaded workbook/GRNstate object, then use that
* If the information cannot be determined, a mechanism should be available that will ask the human user for this information
* The API endpoints for providing these data sets are simply given this information, and do not need to know whether these parameters were human-supplied or derived from GRNstate/workbook context

Hope that makes things a notch clearer. But yes we can clarify further when we meet.

**Comment by afiller1** [comment] 2020-03-19 19:56
Ok, great. So the necessary information to make the query seems to be time points, genes, strain, and data set. And the information we need to get out of the database is the expression data corresponding to each gene for each desired time point.

**Comment by afiller1** [comment] 2020-03-19 20:17
Also, another quick update. Instead of using a Lambda as the API server that connects GRNsight to the database (because apparently I don't have the proper permissions to do that with my AWSEducate account), we made it a bit easier and gave me a little account with the grnsight.cs.lmu AWS account. So the grnsight EC2 will be what hosts the APIs that act as the go-between between GRNsight and the database. I'll include the diagram Dondi drew to explain this all.
![Image from iOS (7)](https://user-images.githubusercontent.com/21373644/77111048-d7f6f480-69e3-11ea-90ab-dd4b0d142e32.jpg)

**Comment by kdahlquist** [comment] 2020-03-19 21:01
I think I know what you mean by "story", so her are some:

1. User uploads a weighted or unweighted SIF file (only has network information) --> GRNsight displays network graph (adjacency matrix stored in JSON) --> user selects dataset, strain, timepoints from our choices from backend database --> nodes are colored --> user exports to a GRNmap workbook, so network and expression data are exported they should have the option to add production and degradation rate data at this point, too, since GRNsight doesn't display it.

2. Number 1, except user uploads a weighted or unweighted GraphML file.

3. Number 1, except that the user uploads a workbook that only has a network or network_optimized_weights sheet

4. User uploads a GRNmap input or output file  --> GRNsight displays network graph, and colored nodes (adjacency matrix stored in JSON, expression data stored in JSON) --> user decides to now select dataset, strain, timepoints from our choices from backend database --> nodes are colored with data from database instead--> user exports to a GRNmap workbook, so network and backend expression data are exported they should have the option to add production and degradation rate data at this point, too, since GRNsight doesn't display it.  They can change the name of the workbook in a Save dialog so they don't overwrite what they originally uploaded.

This raises the question of whether GRNsight should temporarily store the expression data the user uploaded originally if they want to toggle back and forth.  Or does the "Reload" button take care of this?

**Comment by dondi** [comment] 2020-03-23 16:16
Notes from 3/23 Zoom meeting:
* @afiller1 can work with SQL queries pending connection with GRNsight EC2 via Masao
* Upcoming pull request fixes from @Kevboe will help inform UI changes for this task also
* SQL-only is beneficial but not absolutely essential; can do most of the work in SQL followed by final manipulations in Python if certain data conversion operations turn out to be tricky in SQL

**Comment by dondi** [comment] 2020-03-23 16:22
Reminder from @kdahlquist:
* Make sure that a network-only and network-optimized-only workbook will still be acceptable
* Weights can be optionally turned off if available (as before)
* Expression data sheet: Log2optimized is the minimum but Expression sheet on its own is optional

The goal of the back-end database is to fill in or replace information from the workbook with database information.

For export, we will need some “prefab” sheets for compatibility with GRNmap.

**Comment by kdahlquist** [comment] 2020-03-23 17:33
I updated @dondi's previous comment.  I'm noting that here so that you will be notified to look.

**Comment by dondi** [comment] 2020-03-29 01:01
@afiller1 has successfully connected the _grnsight.cs.lmu.edu_ host to her Amazon RDS instance and can communicate with PostgreSQL from _grnsight.cs.lmu.edu_ now. The next step is to write some Python code that will perform database queries remotely. @dondi suggested the [psycopg](https://pypi.org/project/psycopg2/) library to do this; @afiller1 will start setting this up with the goal  being the ability to invoke a query via a Flask route (thus establishing the beginnings of an API server).

**Comment by afiller1** [comment] 2020-03-30 03:59
I did as @dondi outlined in the previous comment and wrote a basic Python program that made a simple query to the database and printed the result. After that, I sort of "converted" this program into a Flask app and returned the result of the query as a JSON object (albeit, a simple JSON object that will probably require some reformatting as the queries grow more complex). But overall, the proper connections are being made, and all that's left to do is format everything to fit the desired queries by building upon the very simple API I have written.

**Comment by dondi** [comment] 2020-03-30 16:52
Having reached this milestone, @afiller1 can start on the eventual production version of the API server. Due to this, it makes sense to start committing this code to a designated place in the repository.

If we stay with Python/Flask, the API server will be its own independent code base but will need to be run as a second server on a different port on _grnsight.cs.lmu.edu_. (e.g., _https://grnsight.cs.lmu.edu:5002/data/expression?....._)

If we switch to Node, the API server can be integrated with the the existing server on _grnsight.cs.lmu.edu_. The same ports would be used, and the route solely determines what function is accessed. (e.g., _https://grnsight.cs.lmu.edu/production/upload_ for reading a workbook, maybe _https://grnsight.cs.lmu.edu/production/data/expression?....._ for accessing the database)

Decision: Switch to Node Express for integrated server with existing functionality. @dondi will help @afiller1 with settings up. Reference link for basic Node HTTP server setup can be found at https://cs.lmu.edu/~ray/notes/httpprogramming/

**Comment by afiller1** [comment] 2020-04-06 16:06
I worked with Dondi to switch to Node Express. I then wrote a "Hello world" API to try it out, and later used the sequelize package to make calls to the database. I then wrote a basic API to make a call to the database.

**Comment by dondi** [comment] 2020-04-06 16:39
Next steps for @afiller1:
* Start designing the final API endpoints for accessing expression data; likely parameters include species and list of genes—there may be more and some might require consultation with @kdahlquist 
* We will also need a "what's available" API endpoint—this will allow the UI to show the user what’s available, from which the user can then pick something
* The API endpoints would then issue the appropriate database queries and return the results; the closer the responses are to the existing `expression` data structure returned from the workbook, the better

**Comment by afiller1** [comment] 2020-04-11 20:08
I have made it so that I have an API that makes a call to the database based on user selection, and the result of that database call is in the format of the expression object within the network object, so this data should be useful in actually making node coloring happen. I little more needs to happen and I'm a bit stuck on my UI stuff (see my UI issue). Once I get that to a point where it's not just an outright error, I'll submit a PR. I'm also a bit challenged at how to actually call the API from the front end but that's a work in progress. I'll continue working over the weekend.

**Comment by afiller1** [comment] 2020-04-12 23:40
I have submitted a PR with what I have done this week. I will put the description of this PR here, because I think it outlines well what I have done today and yesterday:

I have the baseline for making it so that the user can color their GRN using data from our expression database. Currently, I have it working so that, when a user uploads a workbook with no expression data, the nodes will color based on the Barreto data. Currently, it doesn't take in user input as to which data set to use, that's hard coded for now. I was mostly focusing on getting everything connected and inserting the data from the database into the whole network correctly and in the correct JSON format. I mostly tried it out with a file I uploaded with only network data (something funky was happening with demo 3... I will discuss this in the meeting). But node coloring happens once the query is made to the database. I also adjusted the UI slightly, but that is also up for change suggestions. Overall, the baseline functionality of this feature now works to the degree that I've tried it out. I've merged with beta, so there should be no conflicts remaining.

**Comment by afiller1** [comment] 2020-04-20 04:11
I made it so that the timepoints update on the backend side according to which dataset the user selected.

**Comment by dondi** [comment] 2020-04-20 17:15
With the database largely online now, @afiller1 can look into restoring the workbook export feature. @afiller1 will coordinate with @Onariaginosa on a potential merge of her branch, whether via `beta` or direct merge into @afiller1’s branch.

**Comment by afiller1** [comment] 2020-04-26 23:38
I have:
* added the export to excel feature
* figured out how to connect the official database to GRNsight (we still need to toggle stuff on the EC2 so it can run eternally on beta)
* populated this database
* made it so the checkbox to enable node coloring is initially unchecked (this was decently difficult because there are a few different ways in which node coloring is tracked and I had to figure out how to make it so the unchecked box meant the node coloring wouldn't happen, while also figuring out how to change it from the default of coloring automatically)
* made it so the color legend bar as well as its headers, options, and buttons, don't show up until node coloring is happening (goes along with a comment made in #837 ) -- I thought this was better than just having the bar constantly there because there seem to be some more complex methods attached to producing the color bar that I didn't want to disrupt
* adjusted "no expression data" warning to mention the expression database coloring option
* got rid of the weird extension that @dondi pointed out last week that was at the end of my API call
* node coloring using the db now works on the demo sets interestingly enough

I have a few bugs I'm fixing up tonight and then I'll submit a PR for tomorrow. Bugs are:
- [ ] When loaded after a wkbk with expression data, node coloring on a sheet without expression data using expression db doesn't work
- [ ] Using expression db to color a network that already has expression data doesn't fully work

**Comment by kdahlquist** [comment] 2020-04-28 17:25
The Expression Database is not loading for me on beta 4.0.17.

**Comment by afiller1** [comment] 2020-04-29 22:24
Just went onto the EC2 and tried screen -r. Apparently, currently, "there is no screen to be resumed." @dondi Perhaps this has to do with #860 ? Or is beta just down right now?

**Comment by dondi** [comment] 2020-04-29 22:31
Just checked beta; it’s up. Which ec2 are you referring to?

**Comment by dondi** [comment] 2020-04-29 23:51
Ah, just realized why `screen -r` may not have worked—I was still on it 😬 So while it was taken on one of my windows, you weren’t able to get on it.

Having revisited though, I saw these two errors on the console:
```
GET /demo/weighted 200 73.605 ms - 44781
Unhandled rejection SequelizeHostNotFoundError: getaddrinfo ENOTFOUND <database host for beta database> <database host for beta database>:5432
    at connection.connect.err (/home/beta/GRNsight/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:173:24)
    at Connection.connectingErrorHandler (/home/beta/GRNsight/node_modules/pg/lib/client.js:203:14)
    at emitOne (events.js:115:13)
    at Connection.emit (events.js:210:7)
    at Socket.reportStreamError (/home/beta/GRNsight/node_modules/pg/lib/connection.js:71:10)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

Unhandled rejection SequelizeHostNotFoundError: getaddrinfo ENOTFOUND <database host for beta database> <database host for beta database>:5432
    at connection.connect.err (/home/beta/GRNsight/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:173:24)
    at Connection.connectingErrorHandler (/home/beta/GRNsight/node_modules/pg/lib/client.js:203:14)
    at emitOne (events.js:115:13)
    at Connection.emit (events.js:210:7)
    at Socket.reportStreamError (/home/beta/GRNsight/node_modules/pg/lib/connection.js:71:10)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

…so it looks like the current beta doesn’t have the right host name for the RDS instance? @afiller1 can you check the _config.js_ that’s on `beta` to see if it’s right? It was working in the last beta version so maybe something happened with the last pull request?

**Comment by afiller1** [comment] 2020-04-30 01:30
Fixed! Node coloring is working on beta.

**Comment by afiller1** [comment] 2020-04-30 02:30
I propose closing this issue since my initial tasks for this issue have been completed. Additional problems/bugs can be reported in specific issues. @dondi @kdahlquist

**Comment by kdahlquist** [comment] 2020-04-30 02:31
I see it!  Closing this one--good job!

**Closed by kdahlquist** 2020-04-30 02:31 UTC
Labels: CMSI402, feature request, functionality, priority 0, review requested
