### ISSUE TITLE
Unable to upload files on local server on beta branch

### ISSUE THREAD

**Issue by igreen1** [dondi/GRNsight#875] opened 2020-09-15 01:29 UTC
When running locally, uploading a file returns the error 400:"No upload file selected." Error does not exist in remote version but occurs in beta and master branches if run locally.

**Comment by dondi** [comment] 2020-09-17 22:50
I have taken an initial look at this and it is indeed somewhat odd. The _exact_ code, when running from the server, loads files successfully. It is the local development server that's having an issue. Will need to dig in a bit more to determine why this makes a difference.

**Comment by dondi** [comment] 2020-09-25 06:05
The request being made by the web client when submitting the file appears to be the same in both cases, and yet the remote server recognizes the uploaded file while the local server does not.

After multiple trial-and-error attempts, the cause appears to be a version discrepancy: the version of the library that the server uses for extracting the file—[multiparty](https://www.npmjs.com/package/multiparty)—is installed at version 4.1.3. It appears that this version is no longer compatible with newer versions of Node.js. Running an older version of Node.js (which is what the server has) eliminates the error.

Conversely, updating to the latest version of multiparty—version 4.2.2—also eliminates the error. A deep dive of the multiparty commit logs was not done, but it appears that sometime in the version histories of both packages, a compatibility issue arose and was eventually fixed. So the possible solutions are:
* Run GRNsight with an older version of Node.js
* Update multiparty to the current version 4.2.2

The solution to choose can be discussed at the next meeting.

**Comment by dondi** [comment] 2020-09-25 17:42
Temporary fix: `npm install multiparty@4.2.2`

The next beta release will include changes from the team as well as an official update to multiparty 4.2.2.

@dondi and others can test this release with all other import functions to ensure there are no regressions. @dondi will also test beta.

**Comment by dondi** [comment] 2020-09-28 20:44
Beta has now been updated to use `multiparty@4.2.2`. No regressions noticed—local files continue to upload without observed errors. I’ll go ahead and close this.

**Closed by dondi** 2020-09-28 20:44 UTC
Labels: bug, priority 0
