### ISSUE TITLE
Node menu inactivated after loading network from database

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#977] opened 2022-09-07 17:02 UTC
If the first thing I do upon landing on the GRNsight page is to load a network from a database, the node menu is disabled, so I am unable to color the nodes with expression data from the expression database.

I think that now that we have an expression database, the node menu should always be enabled because even if a user doesn't have their own data, they can use the database data.

**Comment by dondi** [comment] 2022-09-07 18:56
Although it is possible to work around this by loading a demo first, and then loading a network from a database, there is now a follow-up issue where node coloring actually doesn’t take place until a dataset is chosen

**Comment by ahmad00m** [comment] 2022-09-14 12:02
I believe if the node coloring should always be enabled this function need to be always enabled. This function is in `setup-handlers.js`, I tried to test it on localhost but I could not connect to it through the multiple attempts I made. So, first I hope to troubleshoot connecting to localhost and then check whether this is the right piece of code that needs to be changed. 

<img width="714" alt="Screen Shot 2022-09-14 at 4 56 44 AM" src="https://user-images.githubusercontent.com/75926755/190147371-8b0f0e75-452f-4826-949f-0a3bef6b726e.png">

**Comment by ahmad00m** [comment] 2022-09-14 16:28
UPDATE 
I tried to run the localhost on my laptop and it was able to connect to the server; however, I still got an error in my console and I was unable to load demos.

<img width="1440" alt="Screen Shot 2022-09-14 at 9 25 17 AM" src="https://user-images.githubusercontent.com/75926755/190210440-727f24ea-ba57-4f94-874b-6c6aab762396.png">

**Comment by dondi** [comment] 2022-09-14 19:03
@ahmad00m Regarding node coloring, I would agree that it is appropriate for it to be always enabled now, except where there is no network loaded

Go ahead and start a branch to work on it, or possible pair w/ @Sarronnn since she will also benefit from doing more of these types of fixes

**Comment by dondi** [comment] 2022-09-14 19:06
For the demo errors, both @Onariaginosa and @dondi confirmed that their local builds are loading demos successfully, so that looks like a localized issue

**Comment by dondi** [comment] 2022-09-14 19:43
Local build remains unresolved but bug fix could be done as a pair w/ @Sarronnn

**Comment by dondi** [comment] 2022-09-14 23:59
Local issue with @ahmad00m has been fixed. Turns out that it was a specific problem with Node 17. Switching to Node 16 or  18 resolves it; @ahmad00m chose to go to 18 and GRNsight ran successfully

**Comment by ahmad00m** [comment] 2022-09-15 00:02
Here is the linked that helped resolve this issue.
https://stackoverflow.com/a/69789658

**Comment by dondi** [comment] 2022-09-15 00:07
Thanks! I have updated the wiki.

**Comment by Sarronnn** [comment] 2022-09-21 14:31
I wanted to first try @ahmad00m 's fix. But the local host can not connect to the database since it is local, therefore I am not able to see changes I made to the code unless I change my branch to beta. 
 - Does changing my branch to beta mean creating a pull request from beta?
 - What does tunnel with SSH key mean? How do I tunnel with SSH key?   

Big thank you to @ahmad00m for all the help so far!

**Comment by kdahlquist** [comment] 2022-09-21 14:53
@Sarronnn, I could be wrong, but I think you need to pull the beta code into your branch.  This is always a good idea so that you can make sure that your code is up-to-date and also to make sure that there are not any conflicts with what you are doing.  I also think that you will need to run a local copy of the database when you are running your code locally.  

@dondi or @Onariaginosa can chime in if I'm wrong or to clarify the process.

**Comment by ahmad00m** [comment] 2022-09-21 17:13
This bug is associated with database and in order to determine the change in code fixes the bug we need to tunnel to database using the ssh key or make a pull request to merge with beta (if you are sure the code written fixes the bug). Thanks to @Onariaginosa for spending time to teach me how to do this process, but as of right now the primary fix didn't fix this issue and I require more time to look where the code needs to be changed. I have some time later in the week to meet with @Sarronnn to go over the process and perhaps fix this bug together.

**Comment by dondi** [comment] 2022-09-21 19:19
After discussing this issue during the meeting, the preferred approach for developers on the team will be to install and run their own copy of PostgreSQL on their respective devices

- Some course notes on installing PostgreSQL: https://dondi.lmu.build/share/db/postgresql-setup-day.pdf
- Configuration can be found in _server/config/config.js_
- Database connection logic can be found in _server/dals_

@Onariaginosa, @ahmad00m, and @Sarronnn will plan a meeting during the week to walk through process, with @dondi being available to consult just in case. Original data files have been linked to under separate cover and may need to updated to @Onariaginosa’s latest copy

We will also take advantage of this to review our database documentation and loader scripts in the _database_ folder of the repository. The hope is to get the documentation to a point where new members can also walk through it in order to get up and running (perhaps something for @ntran18 to try in the future)

**Comment by dondi** [comment] 2022-09-21 19:20
Above comment has been pulled out as a separate issue, #988

**Comment by ahmad00m** [comment] 2022-10-12 02:46
I believe this issue is resolved. I was able to locate the node coloring function in the `update-app.js` and make it to be always on (it will default to expression data from Barreto_2012_wt data) when genes are being selected from database.

Here is how it looks. I can also demonstrate this during the meeting.
![1](https://user-images.githubusercontent.com/75926755/195237580-d213c834-3d95-4ee0-a242-37d094ef56c6.png)

![2](https://user-images.githubusercontent.com/75926755/195237534-5754c85a-d8c8-40bf-bc11-a7f3b49580ce.png)

**Comment by Sarronnn** [comment] 2022-10-12 17:14
- When searching for genes in "Load Database", there was no result: 
    -  <img width="623" alt="Screen Shot 2022-10-12 at 10 03 14 AM" src="https://user-images.githubusercontent.com/89826597/195406146-7daf180e-f760-4587-8115-0933b1206b52.png">
  - So, I had to check to see if the database was set up correctly.
       - To do this, I had to directly inspect the tables by running some SQL queries.

**Comment by Sarronnn** [comment] 2022-10-12 17:20
- Met with Ona to go over how to run some SQL queries to directly inspect the tables. 
     - I made sure I was checking the spring2022 schema and not the public. 
<img width="623" alt="Screen Shot 2022-10-12 at 10 15 57 AM" src="https://user-images.githubusercontent.com/89826597/195406975-ae8f48da-8a61-48f2-a05f-380fa9652c8a.png">

<img width="623" alt="Screen Shot 2022-10-12 at 10 16 09 AM" src="https://user-images.githubusercontent.com/89826597/195407038-76391c55-07e6-4f7c-9ff0-142fd4c30fbd.png">

     - Database was not empty: But why is it still not finding the gene?
     - Also pulled from Ona's branch and tried:
         - Same error persisted:
   
        -  <img width="1394" alt="Screen Shot 2022-10-12 at 10 20 08 AM" src="https://user-images.githubusercontent.com/89826597/195407537-e31df734-c447-4ffc-9047-bc1365c54f57.png">

**Comment by Sarronnn** [comment] 2022-10-12 17:22
Met with Ona to go over how to run some SQL queries to directly inspect the tables.
I made sure I was checking the spring2022 schema and not the public.
<img width="623" alt="Screen Shot 2022-10-12 at 10 15 57 AM" src="https://user-images.githubusercontent.com/89826597/195407888-9e844de4-7a65-4537-925f-15fcbc2e10db.png">

<img width="623" alt="Screen Shot 2022-10-12 at 10 16 09 AM" src="https://user-images.githubusercontent.com/89826597/195407938-89dbee02-2cfb-4f8a-8d3f-0f895e566cc7.png">

 - Database was not empty: But why is it still not finding the gene?
 - Also pulled from Ona's branch and tried:
     - Same error persisted:

<img width="1394" alt="Screen Shot 2022-10-12 at 10 20 08 AM" src="https://user-images.githubusercontent.com/89826597/195407822-4c0df024-1b21-4463-b65c-c175450600f5.png">

**Comment by dondi** [comment] 2022-11-02 19:35
Already merged and placed in beta; got distracted by time zone issue

**Closed by dondi** 2022-11-02 19:35 UTC
Labels: bug, functionality, priority 0, review requested
