### ISSUE TITLE
Refactoring codebase

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#234] opened 2015-10-01 23:34 UTC
@NAnguiano is in the middle of refactoring the entire GRNsight codebase.

**Comment by dondi** [comment] 2015-10-22 23:35
Refactoring work continues, but is resulting in changes that might affect the external interface, so @NAnguiano has moved her work to a *refactoring* branch. A merge can take place when she is done.

**Comment by NAnguiano** [comment] 2015-10-29 21:43
So here's the current status of this. I broke it up into sections because it felt like a wall of text.

##### A note on the spreadsheet controller and graph.js
I've been working on completely refactoring the code for upload.js, moving in a bit to graph.js as required. I paused most of my work on graph.js due to the new structure of the network that will be passed in. I figured it would be easiest to just wait until I saw what that would look like before beginning to make any changes that may need to be undone later. This is also why no work has been done on the spreadsheet controller that has been committed. Now that I've confirmed what will likely be the basic structure, development will begin in earnest on those two files. 

##### Sliders
The most significant new thing is "sliders.js", which contains two objects that handle the functionality of the sliders. Most slider handling functionality has been removed from upload, since I felt it made more sense for upload to contain things that related to uploading files than those related to slider control. Let me know what you think! The objects can be moved elsewhere if desired.

##### New site behaviors
There's been some new site behaviors added in that I wanted to note, just in case they were undesired. 
1. When the user locks the sliders, the reset button also becomes greyed out. Before it was completely usable, but now the user cannot reset the sliders if they are locked. However, I retained the ability for the user to undo a reset while the sliders are locked. Should the undo reset button be greyed out as well? It wouldn't be hard to implement.
2. I greyed out the "undo reset" settings option when the undo reset button is disabled. I figured that it wasn't greyed out originally due to a big, but I figured I'd note it anyways.

##### Changes to force handlers
Though upload.js is the most significantly altered file, there have been minor changes to graph.js, particularly where the force handlers are concerned. Previously, when the user would upload a file, the handlers for controlling the sliders were unbound, then rebound with versions that applied the force to the graph. Now, the 112 lines that originally performed that function have been replaced with two lines. I feel this way is more efficient and a lot prettier and less redundant, but let me know what you think. 

##### Wrapup
The structure of upload.js is pretty different than before. Most notably, there's a ton of constants, since I removed pretty much every magic number and id from wherever it felt reasonable to do so. This way, if they ever change (which they already have), it's really easy to just change it in one place and have the changes apply elsewhere.

Upload.js will continue to change, as I still have a few things I want to add and change. Sliders.js is the same way, since I still see places for improvement. But most of my efforts now will be focused on graph.js and the spreadsheet controller now that initial refactoring is done on upload an the sliders.

whoo this ended up a lot longer than I meant it to. Let me know if everything makes sense or if there's any confusion - I wrote this on my phone and typing on phones is hard

**Comment by kdahlquist** [comment] 2015-10-29 23:40
We have broken out the reset button behavior as a separate issue #245 .  The rest is clear.

**Comment by kdahlquist** [comment] 2015-11-06 00:13
@NAnguiano is working on #234, #204, and #241 together at the same time.  Using the new version node.js is causing a lot of changes because it is so different than what it was before.

**Comment by dondi** [comment] 2016-01-20 20:14
To get our heads into this issue, we did the following:
1. Change to "refactoring" branch and run unit test suite: all 135 tests passed.
2. Run GRNsight server: server initially ran without issues.
3. Run GRNsight client: server initially ran without issues.
4. Load GRNsight in a browser: web page opened without errors.
5. Open a demo sheet: sheet came out OK.
6. Upload a sampling of files: files all loaded as expected.

Conclusion: `refactoring` is in a stable state. Next step is to review the code in light of the notes she made in the above comment to see how far she might have gone.

**Comment by dondi** [comment] 2016-01-20 20:19
Having confirmed stability of the current `refactoring` branch, the next task is to review Nicole's status comment above, section by section, then examine the existing `refactoring` code to assess precisely the current state of the work at this time. Based on what we see about this state (e.g., already done vs. still in progress vs. not started, etc.), we can decide on how to proceed with each line of change.

As findings are made, it would be ideal to put this in writing as comments following this one.

**Comment by dondi** [comment] 2016-01-20 20:24
One more thing to include is the state of the node-xlsx (issue #204), which she does not mention in the comment above but I think was also part of what she was trying to do in this `refactoring` branch.

**Comment by anuvarsh** [comment] 2016-01-25 06:48
After an initial pass through all of Nicole's updates in one of the previous comments, here are my observations:
* Sliders.js is a brand new file that did not previously exist on it's own prior to the refactoring. As Nicole mentioned in her comment, all of the code in upload.js that was concerning the sliders (and therefore not concerning the actual uploading of the file) was moved to sliders.js. I scrolled through to test the readability and I mostly understand all of the functions, though I do need to revisit some code (the `configureSliderControllers` and `configureForceHandlers` functions in particular).
* For the most part, upload.js has been completely rewritten/restructured to follow object oriented practices. Within the `loadGRN` function, much of the code is similar enough to what was written before. Some work that can potentially be done is moving the code that displays the errors into it's own function (similar to `displayWarnings`). Beyond that, I don't immediately see anything else that is pressing with this file.
* Nicole mentioned that she has not done much work to the spreadsheet controller that has been committed. This has been confirmed - the spreadsheet controller is still dependent on the older version of node-xlsx and has not been refactored.
* Some new site functionalities (i.e. the "reset silders" button being greyed out when sliders are locked) were reported and confirmed. I vaguely remember discussing that these new functionalities were desired, but we can revisit this topic at our next meeting.

Next, I will look at the 112 lines in graph.js concerning the set up of the force handlers that were condensed into two lines.

**Comment by kdahlquist** [comment] 2016-01-27 20:04
@anuvarsh will acclimate to this code some more and then we will merge it into beta (aiming for closing this out next week).  @mihirsamdarshi and @anuvarsh will meet face to face this week to do a code walkthrough.

**Comment by anuvarsh** [comment] 2016-02-01 01:24
@mihirsamdarshi and I met earlier today and did a quick code walk through. Both of us are fairly comfortable with the changes that have been made. We will be ready to merge the refactoring branch into beta at our upcoming meeting this week.

**Comment by dondi** [comment] 2016-02-03 20:00
`refactoring` branch has been merged into `beta` and deleted. All tests still pass.

**Closed by dondi** 2016-02-03 20:00 UTC
Labels: functionality, node coloring, priority 0
