### ISSUE TITLE
Moving entire graph with "grab hand" moves top and left boundary that individual genes can be moved to

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#804] opened 2019-10-07 21:24 UTC
I'm not sure how to describe this, but here goes:

Currently, when restrict graph to view port is not checked, we allow the genes to be moved manually beyond the viewport to the right and bottom, but we do not allow them to move beyond the top or left side of the viewport.

I noticed that when I moved the entire graph, by grabbing it with the hand, it changes the top and left boundary for a node to below the viewport.  I.e., I can't manually drag the node beyond an invisible barrier.  

I can demo this in the meeting if it's not clear, just want to record it before I forget.

**Comment by dondi** [comment] 2020-09-18 18:28
At the meeting we could not replicate this but @igreen1 can do a deeper dive to verify.

**Comment by igreen1** [comment] 2020-09-19 00:21
This issue yet lives!

I was wrong. I am able to move the graph out of bounds but this issue is for the nodes themselves. I am still unable to move a /node/ (gene) beyond the viewport, but the graph/network as a whole can be moved beyond the viewport.

**Comment by luluriffic** [comment] 2020-10-09 16:48
Issue isn't consistent! Sometimes I'm able to move a node past the left boundary, but not the top, or past the top, but not the left after moving the whole graph/network. Bizarre and I will investigate further this week.

**Comment by dondi** [comment] 2020-10-09 18:23
After discussing this further during the meeting, the intended behavior for "Restrict Graph to Viewport" was refined further as follows:
* When "Restrict Graph to Viewport" is turned _off_, the graph and pan/zoom controls are allowed to traverse a pseudo-infinite 2D coordinate space
* When "Restrict Graph to Viewport" is turned _on_, the restriction to a viewport currently affects the nodes but not the pan/zoom controls—but _it should_

1. Pan (arrows + center button) should no longer pertain to movement of the "camera" but should be movement of the entire graph within the coordinate space (a.k.a. artboard). Thus, when "Restrict Graph to Viewport" is turned on, the arrow keys and center button should still move _the entire graph_ but _solely within the visible boundaries_. When "Restrict" is off, the arrows will still work but allow the graph to move within the artboard without restrictions.
2. Zoom should still work when "Restrict" is turned on, but the zoom-out should be restricted to some fixed percentage past the artboard and the gray box representing the viewport should be invisible; zoom-in should still work but is limited to the physical size of the graph—i.e., when "Restrict" is turned on, the user should not be able to zoom to a point where the entire graph isn't visible.

**Comment by dondi** [comment] 2020-10-16 17:39
@luluriffic was able to change the behavior of the arrows and will issue a PR when that aspect is ready so that we can move incrementally.

The grab-hand behavior will need deeper changes and she will continue to work on that.

**Comment by dondi** [comment] 2020-10-16 17:40
@luluriffic will also continue on to the Zoom behavior when ready.

**Comment by luluriffic** [comment] 2020-10-23 16:45
PR has been issued for the arrow behavior. No new breakthroughs in the zoom function or grab hand behavior, but now familiarized with the associated code. Corrected the gray border around the viewport when graph is restricted to viewport.

**Comment by dondi** [comment] 2020-10-23 17:43
Broken up into #888 (which has been merged into beta), and #889, with additional smaller issues anticipated to be "peeled off" as needed.

**Comment by dondi** [comment] 2021-01-14 00:15
In order to help @luluriffic get some foundation on D3.js, the following links are recommended:
* https://github.com/d3/d3/wiki/Tutorials (with emphasis on the headlined tutorial https://observablehq.com/@d3/learn-d3)
* https://bost.ocks.org/mike/circles/
* https://bost.ocks.org/mike/join/

**Comment by igreen1** [comment] 2021-03-10 19:22
A solution for this issue #889 and #888 was found, but still has issues. The graph can be moved (and this had been implemented). The issue was that `d3.forceSimulation` was set such that `center` was always the centre of the screen

However, now the graph does not start in the centre of the screen. While @igreen1 could simply force this by moving the graph the center, a more elegant solution likely exists. @igreen1  will investigate

**Comment by igreen1** [comment] 2021-03-17 20:26
The graph (not the camera) now moves in commit 7ceca9e5c25f5a6aed5a03d8a08a68945031bd0f
This is the desired functionality

The zoom is limited for zooming in but not zooming out

**Comment by dondi** [comment] 2021-03-17 23:13
Sounds like @igreen1 just needs a little more refinement and this will be ready for a pull request.

**Comment by igreen1** [comment] 2021-03-24 19:06
Fixed this issue by having the grab hand function move the graph instead, as discussed.

This fix extends to the buttons. the `center` was fixed as well.

However, issues persist with the zoom. While @igrreen1 was able to limit the zoom to approximately 10% in and out, this is not quite the desired functionality. @igreen1 can find the size of the graph and can limit the zoom using that, but if the graph is non-centered, the math for this becomes a little more complicated. @igreen1  has developed an algorithm but would like to discuss it with @dondi to see if a better solution exists.

**Comment by dondi** [comment] 2021-03-24 23:02
Clarification on zoom out desired behavior: go ahead and allow zoom out, but just ensure that the graph does not cross the viewport boundary (no gray box but behavior will be as if the box is still there). Maximum zoom-in is 100% (i.e., cannot get bigger than the viewport).

**Comment by dondi** [comment] 2021-03-24 23:12
Decision on pan behavior: when Restrict Graph to Viewport is active, just disable panning entirely, because there will be no reason to do so. Current panning behavior when Restrict Graph to Viewport is inactive can be retained.

**Comment by igreen1** [comment] 2021-04-07 20:27
commit 35819f3d0320b9c7069c0434a289e0ea6afb2d9b fixes this issue by having viewport controls disappear when restrict viewport is used. Current panning behaviour was regressed to account for node drifting without much issue. 

Zoom was reset to 100% when restrict graph is set, though this can be changed very easily if necessary. (I figured it worked better but no worries if not)

**Comment by dondi** [comment] 2021-04-07 22:58
This was demoed at the meeting and looks good.

One small tweak: rapid clicks on an arrow button makes the browser select the arrow as text; this is CSS property, if applied to the arrow “button” element, should prevent that behavior: https://developer.mozilla.org/en-US/docs/Web/CSS/user-select

(I think you want to go for `user-select: none` but play with it either way)

**Comment by ahmad00m** [comment] 2021-04-26 23:20
From my understanding the D-pad should be disabled entirely when restrict graph to viewport is selected, but this is not the case for graph in drawn in beta because the D-pad still works when restrict graph to viewport is selected.

**Comment by igreen1** [comment] 2021-04-28 17:24
@igreen1  am unable to reproduce this locally, so it is something to do with putting it on the website. Tried a solution from [stackoverflow](https://stackoverflow.com/questions/15848813/jquery-show-hide-function-does-not-work). It doesn't /break/ the fix locally, but cannot test if it actually fixes the issue in beta on the website. Interesting bug all around

Commit 8136b2f1cb1e7fbc6960bdc05a31a0d14f89f351 addresses this issue by adding `$(document).ready()` are a pre-req to `.hide()` and `.show()`. The only way to test this appears to be by merging to beta, annoying. If this commit doesn't fix it, will need to work with @dondi  to better debug

**Comment by Onariaginosa** [comment] 2021-04-28 23:30
The pr #927 fixed this issue!

**Closed by Onariaginosa** 2021-04-28 23:30 UTC
Labels: bug, functionality, priority 0, review requested
