### ISSUE TITLE
GRNsight beta v4.0.17 appears crashed, won't load Excel or demos

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#860] opened 2020-04-29 05:41 UTC
GRNsight beta v4.0.17 appears crashed; it won't load Excel files or demos.  This happened after I tried loading "kev-fake-data-bad-species.xlsx" a couple of times in a row from issue #827 

I'm stuck now until the server can be restarted.

**Comment by dondi** [comment] 2020-04-29 06:40
I have restarted the beta server and it started loading demos and files again for me after that. The server itself wasn't down but it was certainly in a bad state, returning `50x` error status codes on attempting to load things (before it was restarted).

The only hint that something was off when I looked at the `screen` log was this exception:
```
POST /upload 200 126.443 ms - 11311
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 128.175.245.202:443
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1153:14)
[nodemon] app crashed - waiting for file changes before starting...
```
Notice that this was indeed upon a `POST /upload` so I won’t be surprised if this coincides with the _ kev-fake-data-bad-species.xlsx_ file attempt.

At this point this code contains changes by both @Kevboe and @afiller1 so if anyone can try loading this file on a local server then this might help track down the issue. I’ll take a look when I get the chance. Until then, let’s avoid loading this file into the `beta` server until the root cause can be determined.

**Comment by dondi** [comment] 2020-04-29 06:48
I tried to load this file on a local development server of GRNsight multiple times and could not replicate the error. Looks like this one will need more digging. (P.S. I downloaded the file that is attached to #848)

**Comment by dondi** [comment] 2020-09-25 18:04
@Onariaginosa will review this to verify if it’s still valid and report back.

**Comment by Onariaginosa** [comment] 2020-09-25 19:26
I can not recreate this issue, on GRNsight beta v4.0.19, so it appears to be resolved.

**Comment by dondi** [comment] 2020-09-29 23:18
Agreed; closing.

**Closed by dondi** 2020-09-29 23:18 UTC
Labels: bug, functionality, priority 0
