### ISSUE TITLE
Bug: set layout to grid layout and click on any demo, layout goes back to force graph

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#1016] opened 2023-01-25 19:49 UTC
Bug found by @ntran18: if you set the layout to grid layout and click on any demo, the layout goes back to force graph, but the menu and button still indicate that it is a grid layout.

The layout should not change.  Also, the menu/buttons should reflect the current state.

**Comment by ntran18** [comment] 2023-02-08 09:09
This bug is interesting. I checked the bug locally, and it didn't appear. It always changes to Force Graph whenever I click on a new Demo, but the bug only appears on our website.

**Comment by dondi** [comment] 2023-02-08 19:57
Upon discussion the issue is more about whether the layout commands are “sticky” state vs. just one-time actions. The checkbox in the menu is misleading and inconsistent with the buttons on the sidebar. Further, due to manual moving of nodes, the notion of “layout as state” isn’t very applicable in the first place

So the desired fix here includes:
* removing the checks from the menu
* possibly rephrasing the menu items to more clearly state that these are commands

**Comment by dondi** [comment] 2023-02-08 20:01
On further examination, looks like Grid Layout as a state because it locks out the force graph parameters—there may be a need for a broader investigation of how these settings interact

We should also look at interactions with the sidebar to see what makes sense and what does not

It might be useful to look at the client-side testing document to see what was expected in the past

@dondi will meet with @ntran18 sometime to walk through the codebase

**Comment by ntran18** [comment] 2023-02-15 02:57
I made the Grid Layout to modify the Force Graph parameters without changing the graph. The Lock Force Parameters are available for both layouts. However, I cannot fix the bug on the topbar when you click on the grid layout and choose any demo, it still shows Grid Layout. I don't know which functions correspond to that feature.

**Comment by ntran18** [comment] 2023-03-13 21:51
I fixed the bug on the topbar when you click on the grid layout and choose any demo, it will show a Force Graph. However, talking with @dondi, he suggested removing the check of the force graph and grid layout to be matched with the left menu.

**Comment by ntran18** [comment] 2023-03-14 22:06
I tried to remove the "checked" property of Force Graph and Grid Layout on the topbar. However, even if I delete the property, the check doesn't remove. I figure out it has to do something with "glyphicon-ok" class. If I remove that class, when you click on Demo, it doesn't automatically display the graph, but you have to click on either "Force Graph" or "Grid Layout" then it will display the graph.

**Comment by dondi** [comment] 2023-03-15 19:15
@ntran18 will check for errors in the log as a next step

**Comment by ntran18** [comment] 2023-03-22 08:04
I was trying to look at the console. However, I think there is a problem with database, I couldn't load the database. The error in the console log is attached. I'm not sure is this because of the database or the `glyphicon-ok` class
<img width="1440" alt="Screenshot 2023-03-22 at 1 03 27 AM" src="https://user-images.githubusercontent.com/108908370/226837744-be4d49ee-79ee-4b05-8118-4fb997fd4d11.png">

**Comment by ntran18** [comment] 2023-04-12 08:14
I fixed this bug by deleting the glyphicon for Force graph option and Grid Layout option. I also make the glyphicon icon smaller to reduce the space between each option.  
<img width="1204" alt="image" src="https://user-images.githubusercontent.com/108908370/231395520-6aae9bca-477f-412d-b413-9095f880df72.png">

**Comment by kdahlquist** [comment] 2023-04-12 18:35
Next step is to make a pull request.  The PR will be reviewed, and then accepted for beta.  Beta will be refreshed and then the bug needs to be confirmed fixed on beta before closing the issue.

**Comment by dondi** [comment] 2023-04-19 19:23
In order to address the autoformatting issues that arose on @ntran18’s branch, we will re-branch from `beta` and manually redo changes (which ultimately were fairly small once figured out) on that new branch with autoformatting turned off on her editor

Once that is done, we can merge from that new branch instead

**Comment by dondi** [comment] 2023-04-19 19:24
To make sure that changes are limited solely to the code needed to fix this issue, the following can be done:
* Invoke `git diff` before add/commit to ensure that the changes will be restricted to just the code-fix changes
* Invoke `npm run lint` to manually fix any formatting errors from the new code

**Comment by dondi** [comment] 2023-04-19 19:26
We can call the branch something like `maika-1016` to be clear that it is focused solely on this issue

**Comment by ntran18** [comment] 2023-04-26 17:56
I create a new branch called maika-1016 and fix the bugs again from that branch

**Comment by dondi** [comment] 2023-04-26 19:29
This was deployed to beta and we observed the following loose ends:
- There is a residual “state” that still “remembers” that Grid Layout was chosen, which is locking out the force parameters
- When in this residual state, the checkbox for Lock Force Parameters and its corresponding menu item do not appear to sync correctly

**Comment by dondi** [comment] 2023-09-12 16:31
The potential fix for this issue should now be in `beta`; let’s run it and verify with intent of closing once verified

**Comment by dondi** [comment] 2023-09-12 16:35
Reviewed during meeting; OK to close

**Closed by dondi** 2023-09-12 16:35 UTC
Labels: bug, functionality, priority 0, review requested
