### ISSUE TITLE
Create test(s) for out-of-memory error caused by some files

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#340] opened 2016-10-04 05:24 UTC
As noted by @NAnguiano in #337:

Beta initially had an out of memory error and had gone down. We should create a test that tests a file that would cause it to go out of memory and ensure that the server doesn't go down.

**Comment by kdahlquist** [comment] 2016-10-10 23:14
The current workaround is that @anuvarsh and @NAnguiano made a cap on the number of errors that the server could handle.  Right now it's set at 1000, but it could be changed.  Actually, I think anything over like 20 errors is sufficient to stop.  No one is going to look at so many errors.

If this avoids the error, this is sufficient to close this one.

The only issue is that if the out-of-memory error is caused by something else.  We don't have a sophisticated enough log on the server side that records the file that was being uploaded right when it died.

**Closed by kdahlquist** 2016-10-10 23:14 UTC
Labels: backlog, bug, testing
