### ISSUE TITLE
Create unit tests for warnings

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#242] opened 2015-10-16 00:06 UTC
Create unit tests for warnings.  @anuvarsh and @mihirsamdarshi are going to work on this together.

**Comment by anuvarsh** [comment] 2015-11-05 20:26
A new set of unit test functions have been written for warnings. These functions check how many of any given warningCode exist in the warnings array. 

The previously made unit test files have been prefixed with "errors-" because they only contain error unit tests. New files were then created that are prefixed with "warnings-" for warning unit tests.

**Comment by kdahlquist** [comment] 2015-11-06 00:05
@anuvarsh and @mihirsamdarshi are working on this.

**Comment by anuvarsh** [comment] 2015-11-13 19:35
Unit tests for warnings have started being written with the following function:
![image](https://cloud.githubusercontent.com/assets/8509674/11155366/e6cfcaaa-89f9-11e5-94d5-7b8726b984ea.png)
and the following code:
![image](https://cloud.githubusercontent.com/assets/8509674/11155370/ec2d4d06-89f9-11e5-8022-6d54f6274e31.png)
but `make test` is returning this error:
![image](https://cloud.githubusercontent.com/assets/8509674/11155377/f2e50724-89f9-11e5-81e2-55a47b8bf13c.png)

After trying to move the `noWarnings` function into the unit test as such:
![image](https://cloud.githubusercontent.com/assets/8509674/11155396/14e45d8e-89fa-11e5-9f0c-6d492de894f4.png)
`make test` is now returning this error:
![image](https://cloud.githubusercontent.com/assets/8509674/11155404/1b2000c2-89fa-11e5-9356-8c2968ac4b54.png)

After playing around with this for some time, I'm not sure what I'm missing since I basically copied, pasted, and modified the error unit test functions. @dondi, I was wondering if you had any insight?

**Comment by anuvarsh** [comment] 2015-11-20 00:32
The second error was simply because the entire path was not included in the unit test so the file could not be found.

The problem with the first unit test is that @anuvarsh wrote the wrong test function (duplicateGeneError instead of noWarnings). This has now been fixed, and all tests are passing.

**Comment by anuvarsh** [comment] 2015-12-11 00:09
Unit tests were created for all modified/updated files currently in beta. The next step is to finish the unit tests for files made by @mihirsamdarshi in his branch.

**Comment by anuvarsh** [comment] 2016-01-20 08:23
New test files have been created for adjacency matrix sheets as well. Unit tests have been created for about 1/2 of the adjacency matrix files. After @mihirsamdarshi 's branch is merged with beta, more unit tests will be able to be written in other folders.

**Comment by kdahlquist** [comment] 2016-01-20 20:01
@anuvarsh had 12 files left last night, so she needs to do those ASAP.  And then we will be done.  @anuvarsh, please close this issue when they are done (you don't have to wait for next week's meeting.)

**Comment by anuvarsh** [comment] 2016-01-26 04:20
While uploading files to beta for the final unit tests, an "Uncaught SyntaxError" error came up in the console with the following message:
![image](https://cloud.githubusercontent.com/assets/8509674/12572414/faab08c4-c3a0-11e5-9252-b15640a12fa4.png)

I will try to source and fix this before continuing with the unit tests.

**Comment by anuvarsh** [comment] 2016-01-27 01:35
I have been running a local copy with no changes and it seems to be working just fine. The last update to upload.js was 3 months ago, so I'm not sure what is going on. Perhaps a quick restart of the server should fix the problem? I ssh'ed into grnsight but the new server needs to be restarted differently than the old screen because I can't seem to switch into any screens that are running `server` or `web-client`. I will wait until the next opportunity have I have speak with @dondi to resolve this issue.

**Comment by kdahlquist** [comment] 2016-01-27 19:59
#238 (server error) prevented @anuvarsh from finishing this.  Now that the server has been restarted, she can work on this again.

**Comment by anuvarsh** [comment] 2016-02-03 17:10
The same server error came up while uploading "extra-data-end-of-sheet-input.xlsx" when I was trying to complete the warnings. Luckily this sheet was one of the last sheets I tried to upload while writing the tests so a majority are done, but all sheets have not been completed due to this error.

**Comment by dondi** [comment] 2016-02-03 17:57
I've restarted the `beta` server (and we can switch to you at the meeting later), but here is an interesting clue:

<pre>
Configuring GRNsight server
CORS host: http://grnsight.cs.lmu.edu
GRNsight server running on port 4000, environment=beta
GET /demo/weighted 200 79ms - 6.29kb
FATAL ERROR: JS Allocation failed - process out of memory
Aborted (core dumped)
</pre>

Note how the error happened after a single action. This leads me to suspect that the specific sheet is more likely to be the culprit. A true memory leak would have required many accumulated uploads.

**Comment by dondi** [comment] 2016-02-03 19:44
@anuvarsh has confirmed that the issue is indeed specifically caused by the file in question, extra-data-end-of-sheet-input.xlsx. Upon inspecting this file, it turns out that it has over 1 million empty rows, for which the GRNsight server would append as many warnings. On the production server, this number of warnings leads nodejs to run out of memory.

**Comment by dondi** [comment] 2016-02-03 19:50
Preceding issue has been separated into issue #253.

**Comment by dondi** [comment] 2016-02-03 19:50
@anuvarsh has the tests all written, but yet to be verified due to the disruption caused by issue #253.

**Comment by anuvarsh** [comment] 2016-02-07 23:50
All unit tests have been written. Closing this issue.

**Closed by anuvarsh** 2016-02-07 23:50 UTC
Labels: priority 0, testing
