### ISSUE TITLE
Export to SVG modifies the graph itself

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#1059] opened 2023-10-17 16:13 UTC
Choosing _Export to SVG_ results in a visual change to the displayed graph. It appears that prepping the exported data “leaks” some changes to the data in memory.

**Comment by ntran18** [comment] 2024-10-17 06:11
I can't reproduce this error.

**Comment by dondi** [comment] 2024-10-23 20:02
Upon testing during the 10/23 meeting, we noted that the root cause of the error appears to be browser-independent but it manifests in different ways:
* In Chrome and Firefox, visual changes do not occur but #1093 does take place
* In Safari, the same root cause (we believe) does change the visual behavior, but does not break dragging (i.e., not #1093)

**Comment by dondi** [comment] 2024-10-23 20:03
Example in Safari; before export:
<img width="481" alt="image" src="https://github.com/user-attachments/assets/21a00608-e83e-458d-aaa0-cdabaae237b7">

After export:
<img width="530" alt="image" src="https://github.com/user-attachments/assets/35643a32-9784-46c9-ad43-84122df0e6e9">

**Comment by ntran18** [comment] 2024-10-25 06:40
When I ran locally, I didn't encounter the issue in Safari, but I couldn't drag the nodes. I fixed it by creating a copy of the current graph and exporting it. Hopefully, this would fix the issue in Safari.

**Comment by kdahlquist** [comment] 2024-11-13 20:30
confirmed fixed in 7.1.17, closing

**Closed by kdahlquist** 2024-11-13 20:30 UTC
Labels: bug, priority 0, review requested
